const fs = require('fs');
const path = require('path');

const main = () => {
    // Path to the 3D contribution graph generated by the action
    const cityDir = path.join(__dirname, '../profile-3d-contrib');
    const cityPath = path.join(cityDir, 'profile-night-rainbow.svg');

    // Check if directory/file exists
    if (!fs.existsSync(cityPath)) {
        console.log(`File not found: ${cityPath}`);
        // List directory for debugging
        if (fs.existsSync(cityDir)) {
            console.log('Contents of profile-3d-contrib:');
            fs.readdirSync(cityDir).forEach(file => {
                console.log(file);
            });
        } else {
            console.log('Directory profile-3d-contrib does not exist.');
        }
        return;
    }

    let content = fs.readFileSync(cityPath, 'utf-8');

    // Remove the background rect
    // The action usually puts a rect with fill at the top
    // Regex to find <rect ... fill="..." ... /> that looks like a background

    // Strategy: Replace specific known backgrounds or the first rect if it covers the whole view

    // Simple and aggressive: Remove "fill="#00000f"" which is the night-rainbow bg color
    // or the default dark #0d1117

    const originalLength = content.length;

    content = content.replace(/<rect[^>]*fill="#00000f"[^>]*><\/rect>/i, ''); // specific color
    content = content.replace(/<rect[^>]*fill="#0d1117"[^>]*\/>/i, ''); // default github dark

    if (content.length < originalLength) {
        console.log('Background rectangle removed.');
    } else {
        console.log('No background rectangle pattern matched. Content unchanged.');
    }

    // Ensure standard xml header isn't broken
    fs.writeFileSync(cityPath, content);
    console.log('Processed 3D City: Transparency Applied');
};

main();
